name: test

on:
  push:
    branches: master

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        repository: CollaboraOnline/online
    - name: git
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        CONTRIBUTORS=$(git log --all --pretty="%an" | sort | uniq)
	echo "$CONTRIBUTORS"
        echo "$CONTRIBUTORS" | wc -l